# Generated by Django 4.2.9 on 2024-02-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
